계정 SKY
TUSER

/*
TMEMBER
회원관리
번호		숫자(6) 	기본키 자동증가
이름		문자(30) 필수입력
아이디	문자(1) 	필수입력 중복방지
암호		문자(20)	필수입력
이메일	문자(320) 중복방지
가입일 	날짜 	기본값 오늘
*/

TUSER
아이디	문자(20)		필수입력 중복방지
이름		문자(30)		필수입력
이메일	문자(320)	


CREATE TABLE TUSER (
    USERID  VARCHAR2(20)  NOT NULL
    , USERNAME VARCHAR2(30)  NOT NULL
    , USEREMAIL VARCHAR2(320) UNIQUE
    , CONSTRAINT TUSER_PK PRIMARY KEY 
  (
    USERID
  ) 
);

INSERT INTO TUSER VALUES ( 'SKY1', 'APPLE', 'APPLE@SKY.COM');
INSERT INTO TUSER VALUES ( 'SKY2', 'BANANA', 'BANANA@SKY.COM');
INSERT INTO TUSER VALUES ( 'SKY3', 'CHRRY', 'CHERRY@SKY.COM');
INSERT INTO TUSER VALUES ( 'SKY4', 'GRAPE', 'GRAPE@SKY.COM');
INSERT INTO TUSER VALUES ( 'SKY5', 'KIWI', 'KIWI@SKY.COM'); // 데이터 삽입
COMMIT;
